Tlotliso
sokoni-online/intern-program pull request #5
Opened 2021-08-11 10:16 UTC by TlotlisoMokatiJohn

2021-08-16 07:39 UTC, gr1d99 commented
Please Resolve the conflicts

2021-08-16 10:59 UTC, gr1d99 requested changes

2021-08-16 10:59 UTC, gr1d99 commented on src/App.js
> +					<Route path="/login" component={Login} />
Add `exact` prop to the **Route** component

2021-08-16 11:13 UTC, TlotlisoMokatiJohn commented on src/App.js
> +					<Route path="/login" component={Login} />
okay sir thank you   thank you and one thing i almost forgot is to control mobile layout.

2021-08-19 10:22 UTC, gr1d99 approved these changes

2021-08-19 10:22 UTC, merged